### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by bmrolo** [bmrolo/quickSSH#1]
- [x] Enable customizable directories, allowing the user to access directories beyond `/Desktop` and `/Downloads`
- [x] Misc. code optimizations
- [x] Include support for AWS CLI

**Comment by bmrolo** [comment]
Created a .quickssh file that allows users to set aliases and paths
